import store from '../stores'
import {
  initializeAuditSession as initAuditSessionRedux,
  addMission,
  setActiveTab,
} from '../stores/AuditStore'
import { AuditMission, AuditSessionStatus } from '../../../types/AuditTypes'

/**
 * Initializes the audit session and creates default audit missions
 */
export const initializeAuditSession = () => {
  // Initialize audit session
  store.dispatch(
    initAuditSessionRedux({
      sessionId: `audit-${Date.now()}`,
      auditName: 'ISO 27001 Certification Audit',
      status: 'active' as AuditSessionStatus,
      startDate: new Date().toISOString(),
      endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days from now
      auditScope: 'Information Security Management System',
      auditTeam: [],
      organization: 'Alhpa Corp', 
    })
  )

  // Create default ISO 27002 control audit missions
  const defaultMissions: AuditMission[] = [
    {
      id: 'a5-1',
      controlId: 'A.5.1',
      title: 'Information Security Policies',
      description: 'Check if the security policies are documented and approved by the Director.',
      status: 'not_started',
      priority: 'high',
      category: 'POLICIES',
      evidenceRequired: ['policy_document', 'director_approval'],
      evidenceCollected: 0,
      completionPercentage: 0,
      assignedTo: '',
      createdAt: new Date().toISOString(),
      dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      targetObjectId: 'director_desk',
      targetRoom: 'Director Office',
    },
    {
      id: 'a6-1',
      controlId: 'A.6.1',
      title: 'Internal Organization',
      description: 'Verify roles and responsibilities in the meeting room with the manager.',
      status: 'not_started',
      priority: 'high',
      category: 'ORGANIZATION',
      evidenceRequired: ['org_chart', 'interview'],
      evidenceCollected: 0,
      completionPercentage: 0,
      assignedTo: '',
      createdAt: new Date().toISOString(),
      dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      targetObjectId: 'meeting_table',
      targetRoom: 'Meeting Room',
    },
    {
      id: 'a7-2',
      controlId: 'A.7.2.2',
      title: 'Security Awareness',
      description: 'Interview employees in the break room about social engineering risks.',
      status: 'not_started',
      priority: 'medium',
      category: 'HUMAN RESOURCE',
      evidenceRequired: ['interview_notes', 'training_records'],
      evidenceCollected: 0,
      completionPercentage: 0,
      assignedTo: '',
      createdAt: new Date().toISOString(),
      dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      targetObjectId: 'vending_machine',
      targetRoom: 'Break Room',
    },
    {
      id: 'a8-1',
      controlId: 'A.8.1',
      title: 'User Registration',
      description: 'Check user access records on the main office workstations.',
      status: 'not_started',
      priority: 'high',
      category: 'ASSET MANAGEMENT',
      evidenceRequired: ['access_records', 'configuration'],
      evidenceCollected: 0,
      completionPercentage: 0,
      assignedTo: '',
      createdAt: new Date().toISOString(),
      dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      targetObjectId: '0',
      targetRoom: 'General Office',
    },
    {
      id: 'a9-4',
      controlId: 'A.9.4.3',
      title: 'Password Management',
      description: 'Verify password complexity and expiration settings on Office PC 1.',
      status: 'not_started',
      priority: 'high',
      category: 'ACCESS CONTROL',
      evidenceRequired: ['config_screenshot', 'policy_check'],
      evidenceCollected: 0,
      completionPercentage: 0,
      assignedTo: '',
      createdAt: new Date().toISOString(),
      dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      targetObjectId: '1',
      targetRoom: 'General Office',
    },
    {
      id: 'a11-2',
      controlId: 'A.11.2.9',
      title: 'Clear Desk & Clear Screen',
      description: 'Ensure no sensitive data is left visible in the Meeting Room.',
      status: 'not_started',
      priority: 'medium',
      category: 'PHYSICAL SECURITY',
      evidenceRequired: ['observation_photo'],
      evidenceCollected: 0,
      completionPercentage: 0,
      assignedTo: '',
      createdAt: new Date().toISOString(),
      dueDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
      targetObjectId: 'meeting_whiteboard',
      targetRoom: 'Meeting Room',
    },
    {
      id: 'a12-1',
      controlId: 'A.12.1.1',
      title: 'Operating Procedures',
      description: 'Verify that IT operating procedures are available in the Office.',
      status: 'not_started',
      priority: 'high',
      category: 'OPERATIONS',
      evidenceRequired: ['procedure_manual', 'interview'],
      evidenceCollected: 0,
      completionPercentage: 0,
      assignedTo: '',
      createdAt: new Date().toISOString(),
      dueDate: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
      targetObjectId: '2',
      targetRoom: 'General Office',
    },
    {
      id: 'a12-4',
      controlId: 'A.12.4.1',
      title: 'Event Logging',
      description: 'Check if system logs are being recorded and secured on PC 3.',
      status: 'not_started',
      priority: 'medium',
      category: 'OPERATIONS',
      evidenceRequired: ['log_files', 'config'],
      evidenceCollected: 0,
      completionPercentage: 0,
      assignedTo: '',
      createdAt: new Date().toISOString(),
      dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
      targetObjectId: '3',
      targetRoom: 'General Office',
    },
    {
      id: 'a13-1',
      controlId: 'A.13.1.1',
      title: 'Network Controls',
      description: 'Inspect network configuration for segregation in the server area.',
      status: 'not_started',
      priority: 'high',
      category: 'COMMUNICATIONS',
      evidenceRequired: ['network_diagram', 'firewall_config'],
      evidenceCollected: 0,
      completionPercentage: 0,
      assignedTo: '',
      createdAt: new Date().toISOString(),
      dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
      targetObjectId: '4',
      targetRoom: 'General Office',
    },
    {
      id: 'a18-1',
      controlId: 'A.18.1.1',
      title: 'Legal Identification',
      description: 'Verify identification of applicable legislation in the Director office.',
      status: 'not_started',
      priority: 'low',
      category: 'COMPLIANCE',
      evidenceRequired: ['legal_registry'],
      evidenceCollected: 0,
      completionPercentage: 0,
      assignedTo: '',
      createdAt: new Date().toISOString(),
      dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
      targetObjectId: 'director_safe',
      targetRoom: 'Director Office',
    },
  ]

  // Add each mission to the store
  defaultMissions.forEach((mission) => {
    store.dispatch(addMission(mission))
  })

  // Set the active tab to missions
  store.dispatch(setActiveTab('missions'))
}

export default {
  initializeAuditSession,
}
